add_rules("mode.debug", "mode.release")
add_requires("catch2")

target("testCdm")
	set_kind("binary")
	set_languages("c++17")
	set_arch("x64")
	add_files("tests/main.cpp", "tests/tests.cpp")
	add_headerfiles("*.h*")
	add_packages("catch2")
	add_includedirs(".")
